server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser

springdoc:
  consumes-to-match: application/json, application/xml
  produces-to-match: application/json, application/xml
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true